pipeline {
    agent any

    environment {
        def myString = "Hello World"
        def myNumber = 10
        def myBool = true
    }

    stages {
        stage("Demo"){
            steps {
                echo "myString vaut: ${myString}"
                echo "myNumber egale a : ${myNumber}"
                echo "myBool est: ${myBool}"
            }
        }
    }
}